backend:
  name: git-gateway
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Static Pages"
    name: "staticPages"
    delete: false
    format: "json"
    files:
      - label: "About Page"
        name: "aboutPage"
        file: "lib/cms/about-page-config.json"
        fields:
          - label: "Main Section"
            name: "mainSection"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "markdown"
              - label: "Headshot"
                name: "headshot"
                widget: "image"
                allow_multiple: false
          - label: "Video Section"
            name: "videoSection"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Video Embed Link"
                name: "video-embed-link"
                widget: "string"
      - label: "Contact Page"
        name: "contactPage"
        file: "lib/cms/contact-page-config.json"
        fields:
          - label: "Form Section"
            name: "formSection"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
      - label: "Landing Page"
        name: "landingPage"
        file: "lib/cms/landing-page-config.json"
        fields:
          - label: "Desktop Background Image"
            name: "desktopBackgroundImage"
            widget: "image"
            allow_multiple: false
          - label: "Main Section"
            name: "mainSection"
            widget: "object"
            fields:
              - label: "Call To Action"
                name: "callToAction"
                widget: "string"
              - label: "Top Newsletter"
                name: "topNewsletter"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Body"
                    name: "body"
                    widget: "markdown"
                  - label: "Mobile Book Cover Image"
                    name: "mobileBookCoverImage"
                    widget: "image"
                    allow_multiple: false
                    hint: "This is only shown on small screens."
              - label: "Bottom Newsletter"
                name: "bottomNewsletter"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Body"
                    name: "body"
                    widget: "markdown"
                  - label: "Mobile Book Cover Image"
                    name: "mobileBookCoverImage"
                    widget: "image"
                    allow_multiple: false
                    hint: "This is only shown on small screens."
  - label: "Series"
    name: "series"
    folder: "lib/cms/series"
    create: true
    identifier_field: "name"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Tag Line"
        name: "tagLine"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "markdown"
      - label: "Books"
        name: "books"
        widget: "relation"
        collection: "books"
        valueField: "title"
        searchFields: ["title"]
        displayFields: ["title"]
        multiple: true
  - label: "Books"
    name: "books"
    folder: "lib/cms/books"
    create: true
    identifier_field: "title"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Tag Line"
        name: "tagLine"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "markdown"
  - label: "Authors"
    name: "authors"
    folder: "lib/cms/authors"
    create: true
    identifier_field: "name"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
